CREATE DATABASE rec DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE rec;

CREATE TABLE users(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	surname VARCHAR(255) NOT NULL,
	slug VARCHAR(255) NOT NULL,
 	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	salt VARCHAR(32) NOT NULL,
	registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
) Engine = InnoDB;

CREATE TABLE objects(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL
) Engine = InnoDB;

CREATE TABLE unos (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	stanje VARCHAR(255) NOT NULL,
	naziv VARCHAR(255) NOT NULL,
	inventarni_broj INT NOT NULL,
	revers VARCHAR(255) NOT NULL,
	razlog VARCHAR(255) NOT NULL,
	note VARCHAR(255) NOT NULL,
	kreiran VARCHAR(255) NOT NULL,
	upisao VARCHAR(255) NOT NULL,
	lokacija VARCHAR(255) NOT NULL,
	id_lokacija INT NOT NULL
	) Engine = InnoDB;
